backend:
  name: git-gateway
  branch: main
media_folder: "assets/uploads" 
public_folder: "/" 

collections:
  - name: "posts"
    label: "Посты"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    fields:
      - { label: "title", name: "title", widget: "string" }
      - { label: "date", name: "date", widget: "datetime" }
      - { label: "body", name: "body", widget: "markdown" }
      - { label: "image", name: "thumbnail", widget: "image" }

publish_mode: editorial_workflow 
